### ISSUE TITLE
Keybindings conflicts for OS-X

### ISSUE THREAD

**Issue by tomv564** [lukexi/stack-ide-sublime#18]
This package now uses two shortcuts (ctrl+e and ctrl+d) that already have a common editing functions in OS-X: ctrl+e is end of line, ctrl+d is delete character. 

Some discussion about binding these keys can be found in https://github.com/sergeche/emmet-sublime/issues/221.

Would you be okay with setting up different default keybindings for OS-X? Something like ctrl+shift+e and ctrl+shift+d?

**Comment by lukexi** [comment]
:ok_hand: by me! I've got no bindings to the current bindings : )
