### ISSUE TITLE
I cannot get some of the features to work...

### ISSUE THREAD

**Issue by cies** [lukexi/stack-ide-sublime#2]
I must admit I'm very new to ST, so probably I'm just no aware of how things work.

I cannot get the errors dialog to show. In the keybindings file (for OSX) I found that `ctrl+e` should be the binding. Did not work. Then I made a Linux version of the keybindings file. Did not work. Then I found that `ctrl+e` is already bound to `slurp-find-buffer`, so I bound it to `ctrl+!`. Still did not work.

While autosuggest while type works, I cannot get `ctrl+space` autocomplete to work, and I also do not see any type into (as shown in the screenshots). I'm not sure what's going wrong here.

It also never showed the "type of expression under cursor" thing, as the screenshot shows.

Other then that installing was a charm and, the feature that works (suggest while typing) works great and is lightning fast.

Thanks!

**Comment by lukexi** [comment]
Sweet, thanks for the report!

I've never quite figured out a good way to diagnose key binding conflicts in Sublime so I'll look around and see if I can find any ideas there.

I'm also not sure how much debug output I left in, but perhaps you could paste some of the output from the Sublime Text console to help diagnose the missing type annotation? You can bring it up with `ctrl-``

**Comment by cies** [comment]
On the error dialogs keybinding for Linux issue I'm still lost. The ST console shows nothing when I press it.

In the ST console I see that a connection with `stack-ide` is made. I had a problem with my $PATH not being recognized, but starting `subl` from de CLI made that problem disappear.

`ctrl+space` does not cause any extra output on the ST console.

Typing an expression does change the console, for every letter it results in some debug output.

Here I'm typing `unpack` starting with the `p` stopping before the `k`:

```
Sending request:  {'contents': {'autocompletionFilePath': 'LambdaCms/Media/Foundation.hs', 'autocompletionPrefix': 'unp'}, 'tag': 'RequestGetAutocompletion'}
Returning:  []
{'contents': [], 'tag': 'ResponseGetAutocompletion'}
source.haskell 
Sending request:  {'contents': {'spanToColumn': 22, 'spanFromLine': 70, 'spanFilePath': 'LambdaCms/Media/Foundation.hs', 'spanFromColumn': 22, 'spanToLine': 70}, 'tag': 'RequestGetExpTypes'}
{'contents': [], 'tag': 'ResponseGetExpTypes'}
source.haskell 
Sending request:  {'contents': {'spanToColumn': 23, 'spanFromLine': 70, 'spanFilePath': 'LambdaCms/Media/Foundation.hs', 'spanFromColumn': 23, 'spanToLine': 70}, 'tag': 'RequestGetExpTypes'}
{'contents': [], 'tag': 'ResponseGetExpTypes'}
```

Is seems from the output that it does not results in anything from `stack-ide`, maybe I've been using ST's default autocompletion?

**Comment by lukexi** [comment]
Ah yes, that was probably it! Looks like stack-ide isn't loading the project correctly. My startup looks like this:

```
stack-ide-sublime loaded.
[<stack-ide-sublime.stack-ide.SendIdeBackendRequestCommand object at 0x10c239510>]
Launching HIDE in  /Users/lukexi/Projects/udpcubes
Sending request:  {'tag': 'RequestGetSourceErrors', 'contents': []}
{'tag': 'ResponseWelcome', 'contents': [0, 1, 0]}
Unhandled response:  {'tag': 'ResponseWelcome', 'contents': [0, 1, 0]}
{'tag': 'ResponseUpdateSession', 'contents': {'progressOrigMsg': '[1 of 7] Compiling Paths_udpcubes   ( /Users/lukexi/Projects/udpcubes/.stack-work/dist/x86_64-osx/Cabal-1.22.2.0/build/autogen/Paths_udpcubes.hs, interpreted )', 'progressNumSteps': 7, 'progressParsedMsg': 'Compiling Paths_udpcubes', 'progressStep': 1}}
{'tag': 'ResponseUpdateSession', 'contents': {'progressOrigMsg': '[2 of 7] Compiling Physics          ( /Users/lukexi/Projects/udpcubes/src/Physics.hs, interpreted )', 'progressNumSteps': 7, 'progressParsedMsg': 'Compiling Physics', 'progressStep': 2}}
{'tag': 'ResponseUpdateSession', 'contents': {'progressOrigMsg': '[3 of 7] Compiling Types            ( /Users/lukexi/Projects/udpcubes/src/Types.hs, interpreted )', 'progressNumSteps': 7, 'progressParsedMsg': 'Compiling Types', 'progressStep': 3}}
{'tag': 'ResponseUpdateSession', 'contents': {'progressOrigMsg': '[4 of 7] Compiling Movement         ( /Users/lukexi/Projects/udpcubes/src/Movement.hs, interpreted )', 'progressNumSteps': 7, 'progressParsedMsg': 'Compiling Movement', 'progressStep': 4}}
{'tag': 'ResponseUpdateSession', 'contents': {'progressOrigMsg': '[5 of 7] Compiling Randoms          ( /Users/lukexi/Projects/udpcubes/src/Randoms.hs, interpreted )', 'progressNumSteps': 7, 'progressParsedMsg': 'Compiling Randoms', 'progressStep': 5}}
{'tag': 'ResponseUpdateSession', 'contents': {'progressOrigMsg': '[6 of 7] Compiling Server           ( /Users/lukexi/Projects/udpcubes/src/Server.hs, interpreted )', 'progressNumSteps': 7, 'progressParsedMsg': 'Compiling Server', 'progressStep': 6}}
{'tag': 'ResponseUpdateSession', 'contents': {'progressOrigMsg': '[7 of 7] Compiling Client           ( /Users/lukexi/Projects/udpcubes/src/Client.hs, interpreted )', 'progressNumSteps': 7, 'progressParsedMsg': 'Compiling Client', 'progressStep': 7}}
{'tag': 'ResponseUpdateSession', 'contents': None}
```

I think when it's not working, you won't see any of the intermediate "Compiling" steps.

One invisible assumption at the moment is that you've opened the same folder that has the .cabal file in it, and that the .cabal file/package is named the same as the folder, so that could something?

And the other thing I've found is that the current version of ide-backend apparently requires you to have the "ide-backend-rts" package available in the package database — i.e. it's listed in the project's `stack.yaml` as a relative directory under `packages`. There's a pull request about to be merged that fixes that annoyance here: https://github.com/fpco/ide-backend/pull/290 — I'm testing it locally and it lifts that annoyance. But I think you should see an error panel with "couldn't find package ide-backend-rts" if that was the problem.

I'll put this all in the README now : )

**Comment by lukexi** [comment]
The pull request I mentioned has been merged, so if you grab the latest ide-backend you can disregard the second part!

**Comment by cies** [comment]
> I think when it's not working, you won't see any of the intermediate "Compiling" steps.

I dont see them. So that will be it.

> One invisible assumption at the moment is that you've opened the same folder that has the .cabal file in it, and that the .cabal file/package is named the same as the folder, so that could something?

I follow that convention for the packages I'm working on.

> And the other thing I've found is that the current version of ide-backend apparently requires you to have the "ide-backend-rts" package available in the package database — i.e. it's listed in the project's stack.yaml as a relative directory under packages. There's a pull request about to be merged that fixes that annoyance here: fpco/ide-backend#290 — I'm testing it locally and it lifts that annoyance. But I think you should see an error panel with "couldn't find package ide-backend-rts" if that was the problem.

That it! I see this panel on _Save_:

```
<command line>: cannot satisfy -package ide-backend-rts
    (use -v for more information)
```

I'll try upgrading `ide-backend`, as adding lines to all my stack.yamls to avoid editor integration problems should not be the way fwd.

Thanks for the elaborate and fast response!

**Comment by cies** [comment]
Hmm. I added `- ide-backend-rts-0.1.3.1` to `extra-deps:` (I'm using `resolver: nightly-2015-07-09`). Then run `stack build` and restarted sublime. The

```
<command line>: cannot satisfy -package ide-backend-rts
    (use -v for more information)
```

error on _Save_ remains.

I think I did not understand correctly how to fix this. Maybe you could provide some steps to install `stack-ide-sublime`. Now it says `First make sure to install stack and stack-ide.` But I think it should now be `First make sure to install stack, then install stack-ide using ide-backend HEAD as follows [...]`.

I'll see if I can get it to work, and contribute the README changes it I get it to work.

BTW: https://github.com/commercialhaskell/stack-ide/commit/756abcbc505f66631531d86d1697145dbb2a1ea4

**Comment by cies** [comment]
Ok. I reinstalled a fresh `stack-ide` with a fresh `ide-backend` (thus HEAD), I used the `stack-ide` instructions as on the README of `stack-ide` (so did not change it according to the BTW notice in my previous post).

It seems to start well now:

```
[<stack-ide-sublime.stack-ide.SendIdeBackendRequestCommand object at 0x7f5fdc5b6810>, <stack-ide-sublime.stack-ide.SendIdeBackendRequestCommand object at 0x7f5fdc5bed10>, <stack-ide-sublime.stack-ide.SendIdeBackendRequestCommand object at 0x7f5fdc5c6b90>]
Launching HIDE in  /home/cies/repos/work/lambdacms/lambdacms-media
Sending request:  {'tag': 'RequestGetSourceErrors', 'contents': []}
{'tag': 'ResponseWelcome', 'contents': [0, 1, 0]}
Unhandled response:  {'tag': 'ResponseWelcome', 'contents': [0, 1, 0]}
{'tag': 'ResponseUpdateSession', 'contents': {'progressOrigMsg': '[1 of 6] Compiling LambdaCms.Media.Message ( /home/cies/repos/work/lambdacms/lambdacms-media/LambdaCms/Media/Message.hs, interpreted )', 'progressNumSteps': 6, 'progressStep': 1, 'progressParsedMsg': 'Compiling LambdaCms.Media.Message'}}
{'tag': 'ResponseUpdateSession', 'contents': {'progressOrigMsg': '[2 of 6] Compiling LambdaCms.Media.Models ( /home/cies/repos/work/lambdacms/lambdacms-media/LambdaCms/Media/Models.hs, interpreted )', 'progressNumSteps': 6, 'progressStep': 2, 'progressParsedMsg': 'Compiling LambdaCms.Media.Models'}}
{'tag': 'ResponseUpdateSession', 'contents': {'progressOrigMsg': '[3 of 6] Compiling LambdaCms.Media.Foundation ( /home/cies/repos/work/lambdacms/lambdacms-media/LambdaCms/Media/Foundation.hs, interpreted )', 'progressNumSteps': 6, 'progressStep': 3, 'progressParsedMsg': 'Compiling LambdaCms.Media.Foundation'}}
{'tag': 'ResponseUpdateSession', 'contents': {'progressOrigMsg': '[4 of 6] Compiling LambdaCms.Media.Import ( /home/cies/repos/work/lambdacms/lambdacms-media/LambdaCms/Media/Import.hs, interpreted )', 'progressNumSteps': 6, 'progressStep': 4, 'progressParsedMsg': 'Compiling LambdaCms.Media.Import'}}
{'tag': 'ResponseUpdateSession', 'contents': {'progressOrigMsg': '[5 of 6] Compiling LambdaCms.Media.Handler.Media ( /home/cies/repos/work/lambdacms/lambdacms-media/LambdaCms/Media/Handler/Media.hs, interpreted )', 'progressNumSteps': 6, 'progressStep': 5, 'progressParsedMsg': 'Compiling LambdaCms.Media.Handler.Media'}}
{'tag': 'ResponseUpdateSession', 'contents': {'progressOrigMsg': '[6 of 6] Compiling LambdaCms.Media  ( /home/cies/repos/work/lambdacms/lambdacms-media/LambdaCms/Media.hs, interpreted )', 'progressNumSteps': 6, 'progressStep': 6, 'progressParsedMsg': 'Compiling LambdaCms.Media'}}
{'tag': 'ResponseUpdateSession', 'contents': None}
{'tag': 'ResponseGetSourceErrors', 'contents': []}
```

I also get the blue boxes around symbols when my cursor is in them and I see the type in the statusbar. Autocomplete with `ctrl+space` is not working yet (I suspect it to be an ST3 issue), but autosuggest is working like a charm (with type and where-is-it-defined info working).

The errors panel is still an issue (same as I originally described on Linux).

Thanks a lot for the help! ST3 now has IDE'ish features for Haskell on my machine. I'm more of an Emacs user, but I want something more beginner friendly. This fits really well, especially when we work out the last issues and Haskell LTS 3 comes with GHC 7.10 which will then ship the current HEAD of `ide-backend` and `stack-ide`. This may be a matter of weeks.

**Comment by cies** [comment]
> One invisible assumption at the moment is that you've opened the same folder that has the .cabal file in it, and that the .cabal file/package is named the same as the folder, so that could something?

Ok. I can confirm this now. Does this sublime plugin work for stack projects that span over multiple packages?

**Comment by lukexi** [comment]
Yay, that's fantastic — thanks for hanging on the bumpy ride : ). 

I'll see if I can figure out why ctrl+space isn't working too (feel free to open issues to keep me from forgetting anything!)

I _think_ it works if you just open each subproject folder in its own window. Internally we call `stack ide <project-name>`, so basically whatever that supports we support too.

Yeah, I think this has the potential to be a _super_ nice Haskell experience. I'm addicted to ST3's buttery-smooth OpenGL interface so I have a lot of trouble moving to other editors, haha.

**Comment by cies** [comment]
> I'll see if I can figure out why ctrl+space isn't working too (feel free to open issues to keep me from forgetting anything!)

Will do.

And about the `ctrl+e` dialog: I think it appears now right away, sometimes I even have trouble closing it (just me being new to ST).

> I think it works if you just open each subproject folder in its own window. Internally we call stack ide <project-name>, so basically whatever that supports we support too.

Ok, great. Cuz I'm in the process of moving LambdaCms repos to multi-repos.

> Yeah, I think this has the potential to be a super nice Haskell experience. I'm addicted to ST3's buttery-smooth OpenGL interface so I have a lot of trouble moving to other editors, haha.

I didn't notice GL, ignorant me. But now you mention it, it is smooth. I noticed yr doing some really cool visual/arts projects in yr twitter. Well done! Must be great to work on that :)
