### ISSUE TITLE
in some cases, error pannel no longer work

### ISSUE THREAD

**Issue by rvion** [lukexi/stack-ide-sublime#28]
in the picture below, we can see that the bottom pannel is empty:

![image](https://cloud.githubusercontent.com/assets/2150990/10783814/b0206a88-7d5a-11e5-809f-69eb0b4995cc.png)

**Comment by rvion** [comment]
code to reproduce:

 ```
module Main where

main :: IO ()
main = do
  putStrLn "hello world"

c = print "tetst" c


b = foldl (+) 0 [0..10]
```

**Comment by rvion** [comment]
code to reproduce:

``` haskell
module Main where

main :: IO ()
main = do
  putStrLn "hello world"

c = print "tetst" c


b = foldl (+) 0 [0..10]
```

ping @tomv564 @lukexi

**Comment by tomv564** [comment]
Hi Rémi - thanks for the helpful sample. I get an expected error about print's arguments, so I'm not hitting the bug this way.

Could you set `"verbosity": "debug"` in the SublimeStackIDE settings, load this demo project again, and paste the console log entries here?

**Comment by rvion** [comment]
It's now working for me too, I guess I did something wrong at that time :)

**Comment by rvion** [comment]
thanks for having taken the time to test it
