### ISSUE TITLE
SublimeStackIde:restart don't work anymore

### ISSUE THREAD

**Issue by rvion** [lukexi/stack-ide-sublime#29]
when I call `restart`
I get this:

``` python
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 520, in run_
    return self.run()
  File "/Users/RemiVion/Library/Application Support/Sublime Text 3/Packages/SublimeStackIDE/application_commands.py", line 14, in run
    StackIDEManager.reset()
TypeError: reset() missing 1 required positional argument: 'settings'
```

To confirm nothing happened, I can delete large portions of the code, than restart the plugin, but it will keeps working instead instead of breaking.

that's a bit annoying to hack on the plugin

**Comment by rvion** [comment]
ping @tomv564 @lukexi

**Comment by tomv564** [comment]
So this issue was easy to fix, but the restart command is only useful for forcing your backend to restart (in case your project files changed etc.)
Can you check if this works? 

I'll add some comments about the plugin restart limitations to https://github.com/lukexi/stack-ide-sublime/issues/30

**Comment by rvion** [comment]
yes, it works :) thanks
