### ISSUE TITLE
stacktrace of stack-IDE error right at the start

### ISSUE THREAD

**Issue by rubenmoor** [lukexi/stack-ide-sublime#8]
Hello,

I'm happy to see haskell tooling improving and I'm looking forward to this project in particular. This is the error I get right in the beginning

[SublimeStackIDE][WARN]: Stack-IDE error:  
Traceback (most recent call last):
  File "/home/ruben/.config/sublime-text-3/Packages/stack-ide-sublime/stack-ide.py", line 530, in <lambda>
    sublime.set_timeout(lambda: self.highlight_errors(contents), 0)
  File "/home/ruben/.config/sublime-text-3/Packages/stack-ide-sublime/stack-ide.py", line 618, in highlight_errors
    span = Span.from_json(proper_span.get("contents"), self.window)
  File "/home/ruben/.config/sublime-text-3/Packages/stack-ide-sublime/stack-ide.py", line 688, in from_json
    from_point = view.text_point(from_line - 1, from_column - 1)
AttributeError: 'NoneType' object has no attribute 'text_point'

**Comment by jcpetruzza** [comment]
Could you perhaps set the log verbosity to "normal" (in `Preferences -> Package Settings -> SublimeStackIDE -> Settings - User`) and then paste a full console log?

**Comment by rubenmoor** [comment]
```
[SublimeStackIDE][NORM]: Starting stack-ide-sublime watchdog
[SublimeStackIDE][NORM]: Initializing window 2
[SublimeStackIDE][NORM]: Launching stack-ide instance for  /home/ruben/code/holger/core
[SublimeStackIDE][DEBUG]: Calling stack with PATH: /home/ruben/.cabal/bin:/home/ruben/.cabal/bin:/usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games:/home/ruben/.local/bin:/home/ruben/.local/bin
[SublimeStackIDE][DEBUG]: Got response:  {'contents': [0, 1, 0], 'tag': 'ResponseWelcome'}
[SublimeStackIDE][NORM]: Unhandled response:  {'contents': [0, 1, 0], 'tag': 'ResponseWelcome'}
[SublimeStackIDE][NORM]: Kicking off window 2
[SublimeStackIDE][DEBUG]: Sending request:  {'contents': [], 'tag': 'RequestGetSourceErrors'}
[SublimeStackIDE][DEBUG]: Got response:  {'contents': {'contents': [], 'tag': 'UpdateStatusRequiredRestart'}, 'tag': 'ResponseUpdateSession'}
[SublimeStackIDE][DEBUG]: Got response:  {'contents': {'contents': [], 'tag': 'UpdateStatusDone'}, 'tag': 'ResponseUpdateSession'}
[SublimeStackIDE][DEBUG]: Got response:  {'contents': [{'errorKind': 'KindError', 'errorSpan': {'contents': {'spanFromLine': 19, 'spanFilePath': 'src/Api/XBRL.hs', 'spanFromColumn': 18, 'spanToLine': 19, 'spanToColumn': 31}, 'tag': 'ProperSpan'}, 'errorMsg': 'Could not find module ‘XBRL.Document’\nUse -v to see a list of the files searched for.'}], 'tag': 'ResponseGetSourceErrors'}
Traceback (most recent call last):
  File "/home/ruben/.config/sublime-text-3/Packages/stack-ide-sublime/stack-ide.py", line 530, in <lambda>
    sublime.set_timeout(lambda: self.highlight_errors(contents), 0)
  File "/home/ruben/.config/sublime-text-3/Packages/stack-ide-sublime/stack-ide.py", line 618, in highlight_errors
    span = Span.from_json(proper_span.get("contents"), self.window)
  File "/home/ruben/.config/sublime-text-3/Packages/stack-ide-sublime/stack-ide.py", line 688, in from_json
    from_point = view.text_point(from_line - 1, from_column - 1)
AttributeError: 'NoneType' object has no attribute 'text_point'
```

**Comment by jcpetruzza** [comment]
Ok, just to make the error more precise: what seems to be happening is that your project fails to build, but the build error is in a file (src/Api/XBRL.hs) that you don't have opened in Sublime.

Could you confirm this is the case? E.g., open the file, save it (so it gets rebuilt) and you should see the build error below.

**Comment by rubenmoor** [comment]
incredible, it works now. I can't reproduce the error above. One thing I changed: my _core.cabal_ was missing one of my modules in `other-modules`. It was not, however, Api.XBRL ...

It's beautiful and so quick! :dancers:

**Comment by jcpetruzza** [comment]
The problem with build errors on non-open files was still there; so I've pushed a fix for it....

**Comment by rubenmoor** [comment]
For completeness sake: The bug appeared when I opened sublime on a directory (oh-my-zsh: `stt`) instead of on a file. Applying your fix, both ways work now.
